#ytdl_preload.conf
# make sure lines do not have trailing whitespace
# ytdl_opt has no sanity check and should be formatted exactly how it would appear in yt-dlp CLI, they are split into a key/value pair on whitespace
# at least on Windows, do not escape '\' in temp, just us a single one for each divider
# keepfaults=no :: if ytdl fails to retrieve a video, anything besides "no" will keep it in the playlist, otherwise the entry is removed so that the script can preload the next video instead

temp=R:\ytdl
keepfaults=no
ytdl_opt1=-N 5
ytdl_opt2=-f bestvideo+bestaudio
